---
title: "Data & Techniques for E-Health"
author: "Thomas"
toc: true
numbersections: true
geometry: a4paper,landscape,top=2cm,bottom=2cm,left=0.5cm,right=0.5cm,heightrounded
version: "PcVersion"
fontsize: 14pt
documentclass: extreport
before-toc: |
  \clearpage
header-includes:
  - \usepackage{charter}
  - \usepackage{titlesec}
  - \titleformat{\chapter}[hang]{\normalfont\huge\bfseries}{}{0pt}{}
---
