---
title: "Data & Techniques for E-Health"
author: "Thomas"
toc: true
numbersections: true
geometry: a4paper,top=2cm,bottom=2cm,left=2.3cm,right=3.5cm,heightrounded,twoside
version: "PrintVersion"
documentclass: extreport
before-toc:
  \clearpage
header-includes:
  - \usepackage{charter}
  - \usepackage{titlesec}
  - \titleformat{\chapter}[hang]{\normalfont\huge\bfseries}{\thechapter}{1em}{}
---
